config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'products#index'

  resources :carts, only: [:index] do
    collection do
      post :reset
      post :add
    end
  end

  resources :products, only: [:index] do
    resource :pricing_rule, only: %i[edit create update]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: orders
#
#  id          :bigint           not null, primary key
#  notes       :text
#  status      :string           default("pending"), not null
#  total_price :decimal(10, 2)   default(0.0), not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Order < ApplicationRecord
  ALLOWED_STATUSES = ['pending', 'in transit', 'completed', 'cancelled'].freeze

  has_many :order_items, dependent: :destroy
  has_many :products, through: :order_items

  validates :status, presence: true, inclusion: { in: ALLOWED_STATUSES }
  validates :total_price, presence: true, numericality: { greater_than: 0.0 }
end

app/models/order_item.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: order_items
#
#  id                     :bigint           not null, primary key
#  price_after_discount   :decimal(10, 2)
#  price_at_purchase_time :decimal(10, 2)
#  quantity               :integer          default(1), not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  order_id               :bigint           not null
#  product_id             :bigint           not null
#
# Indexes
#
#  index_order_items_on_order_id    (order_id)
#  index_order_items_on_product_id  (product_id)
#
# Foreign Keys
#
#  fk_rails_...  (order_id => orders.id)
#  fk_rails_...  (product_id => products.id)
#

class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :price_at_purchase_time, numericality: { greater_than_or_equal_to: 0.0 }, allow_nil: true
  validates :price_after_discount, numericality: { greater_than_or_equal_to: 0.0 }, allow_nil: true
end

app/models/pricing_rule.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: pricing_rules
#
#  id                 :bigint           not null, primary key
#  active             :boolean          default(TRUE)
#  discount_price     :decimal(10, 2)
#  discount_rate      :decimal(5, 2)
#  rule_type          :string
#  threshold_quantity :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  product_id         :bigint           not null
#
# Indexes
#
#  index_pricing_rules_on_product_id  (product_id)
#
# Foreign Keys
#
#  fk_rails_...  (product_id => products.id)
#

class PricingRule < ApplicationRecord
  belongs_to :product

  enum rule_type: { bogof: 'bogof', bulk_purchase: 'bulk_purchase', volume_discount: 'volume_discount' }

  validates :rule_type, presence: true, inclusion: { in: rule_types.keys }
  validates :threshold_quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :discount_price, presence: true, numericality: { greater_than: 0.0 }, if: :bulk_purchase?
  validates :discount_rate, presence: true, numericality: { greater_than: 0.0, less_than: 1.0 }, if: :volume_discount?
  validates :active, inclusion: { in: [true, false] }

  scope :active, -> { where(active: true) }

  def self.rules
    rule_types.keys.map do |type|
      if type == 'bogof'
        ['Buy one Get one Free', type]
      else
        [type.titleize, type]
      end
    end
  end
end

app/models/product.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: products
#
#  id         :bigint           not null, primary key
#  code       :string           not null
#  name       :string           default(""), not null
#  price      :decimal(10, 2)   default(0.0), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_products_on_code  (code) UNIQUE
#

class Product < ApplicationRecord
  has_many :order_items
  has_many :orders, through: :order_items

  has_one :pricing_rule

  validates :code, presence: true, uniqueness: true
  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0.0 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  def index
    @cart_items = session[:cart] || {}
  end

  def add
    session[:cart] ||= {}

    product_code = params[:product_code]
    quantity = params[:quantity].to_i

    if product_code.present? && quantity.positive?
      CartAfterPricingRule.new(session[:cart], product_code, quantity).apply_pricing_rule

      redirect_to products_path, notice: 'Product added to cart successfully!'
    else
      message = product_code.blank? ? 'No product code found' : 'Invalid product code or quantity'
      redirect_to products_path, alert: message
    end
  end

  def reset
    session[:cart] = {}
    redirect_to products_path, alert: "Cart reset successfully!"
  end
end

app/controllers/pricing_rules_controller.rb
# frozen_string_literal: true

class PricingRulesController < ApplicationController
  before_action :set_product

  def edit
    @pricing_rule = @product.pricing_rule || @product.build_pricing_rule
  end

  def create
    @pricing_rule = @product.build_pricing_rule(pricing_rule_params)
    if @pricing_rule.save
      redirect_to products_path, notice: 'Pricing plan created successfully.'
    else
      render :edit
    end
  end

  def update
    @pricing_rule = @product.pricing_rule
    if @pricing_rule.update(pricing_rule_params)
      redirect_to products_path, notice: 'Pricing plan updated successfully.'
    else
      render :edit
    end
  end

  private

  def set_product
    @product = Product.find(params[:product_id])
  end

  def pricing_rule_params
    params.require(:pricing_rule).permit(:discount_price, :discount_rate, :rule_type, :threshold_quantity, :active)
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/carts/_details.html.slim
- if @cart_items.present?
  - @cart_items.each do |product_code, details|
    .card.mb-3
      .card-header
        | Product Code: #{product_code}
      .card-body
        h5.card-title
          | Price: #{number_to_currency(details["price_at_purchase_time"])}
        p.card-text
          - if details["quantity"]
            p
              | Quantity: #{details["quantity"]}
          - if details["discount_type"]
            p
              | Discount Applicable: #{details["discount_type"]}
          - if details["free_items"]
            p
              | Free Items: #{details["free_items"]}
          - if details["total_items"]
            p
              | Total Items: #{details["total_items"]}
          - if details["total_discount"]
            p
              | Total Discount: #{number_to_currency(details["total_discount"])}
          - if details["total_payable"]
            p
              | Total Payable: #{number_to_currency(details["total_payable"])}
  = link_to 'Reset Cart', reset_carts_path, class: 'btn btn-danger', method: :post, id: 'resetCartLink'
- else
  | Your cart is empty!

app/views/carts/index.js.erb
$("#viewCartModal .modal-body").html('<%= j render partial: "carts/details" %>');
$('#viewCartModal').modal('show')

app/views/layouts/_header_layout.html.slim
= csrf_meta_tags
= csp_meta_tag
= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/_jgrowl_notifications.html.slim
- if flash[:notice].present?
  javascript:
    $.jGrowl("#{flash[:notice]}", { theme: 'success'})
- if flash[:alert].present?
  javascript:
    $.jGrowl("#{flash[:alert]}", {theme: 'error'})

app/views/layouts/_top_nav_bar.html.slim
header
  nav.navbar.navbar-expand-md.navbar-dark.fixed-top.bg-dark
    .container-fluid
      a.navbar-brand href="#" Ecommerce System
      button.navbar-toggler aria-controls="navbarCollapse" aria-expanded="false" aria-label=("Toggle navigation") data-bs-target="#navbarCollapse" data-bs-toggle="collapse" type="button"
        span.navbar-toggler-icon

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | BE Assignment Junior
    = render 'layouts/header_layout'
  - if ['sessions' , 'registrations'].include?(controller_name)
    body.text-center
      main.form-signin
        = yield
  - else
    body.d-flex.flex-column.h-100
      = render 'layouts/top_nav_bar'
    main.flex-shrink-0
      .container
        = yield

= render 'layouts/jgrowl_notifications'

app/views/pricing_rules/edit.html.slim
= form_with(model: @pricing_rule, url: product_pricing_rule_path, local: true, class: "my-4") do |form|
  h3.pt-5.mt-6
    | Manage Pricing Rule

  .mb-3.mt-3
    = form.label :rule_type, class: "form-label"
    = form.select :rule_type, PricingRule.rule_types.keys.map { |type| [type.titleize, type] }, {include_blank: 'Select a rule type', }, { class: "form-select", id: "rule_type_select" }

  .mb-3#discount_price_field
    = form.label :discount_price, class: "form-label"
    = form.text_field :discount_price, class: "form-control"

  .mb-3#discount_rate_field
    = form.label :discount_rate, class: "form-label"
    = form.text_field :discount_rate, step: 0.01, class: "form-control"

  .mb-3
    = form.label :threshold_quantity, class: "form-label"
    = form.number_field :threshold_quantity, class: "form-control"

  .mb-3
    = form.label :active, class: "form-check-label"
    = form.check_box :active, class: "form-check-input mx-3"

  = form.submit @pricing_rule.new_record? ? 'Create Pricing Plan' : 'Update Pricing Plan', class: "btn btn-primary"

javascript:
  $(document).on('turbolinks:load', function() {
    const $ruleTypeSelect = $('#rule_type_select');
    const $discountPriceField = $('#discount_price_field');
    const $discountRateField = $('#discount_rate_field');

    function toggleFields() {
      const ruleType = $ruleTypeSelect.val();
      $discountPriceField.toggle(ruleType === 'bulk_purchase');
      $discountRateField.toggle(ruleType === 'volume_discount');
    }

    toggleFields(); // Call on load in case there is a preselected value
    $ruleTypeSelect.on('change', toggleFields);
  });

app/views/products/index.html.erb
<div class="container mt-5">
  <div class="d-flex justify-content-between mb-3 pt-4">
    <h2>Products List</h2>

    <%= link_to 'View Cart', carts_path, class: 'btn btn-success', remote: true, id: 'viewCartLink' %>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th>Code</th>
        <th>Name</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Add to Cart</th>
        <th>Manage Pricing Plan</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.code %></td>
          <td><%= product.name %></td>
          <td><%= number_to_currency(product.price, unit: "€") %></td>
          <td>
            <%= form_with url: add_carts_path, method: :post do |form| %>
              <%= form.number_field :quantity, in: 1..10, step: 1, value: 1, class: "form-control" %>
          </td>
          <td>
              <%= form.hidden_field :product_code, value: product.code %>
              <%= form.submit "Add to Cart", class: "btn btn-primary" %>
            <% end %>
          </td>
          <td>
            <%= link_to 'Manage Pricing Rules', edit_product_pricing_rule_path(product_id: product.id), class: 'btn btn-info', id: 'viewCartLink' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="modal fade" id="viewCartModal" tabindex="-1" aria-labelledby="viewCartModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="viewCartModalLabel">Cart Details</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <turbo-frame id="cart">
        </turbo-frame>
      </div>
    </div>
  </div>
</div>